server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: departmentCircuitBreaker
                fallbackuri: forward:/departmentServiceFallBack

resilience4j:
  circuitbreaker:
    instances:
      departmentCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000
      userCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 10000